image:
  file: .gitpod.Dockerfile
tasks:
  - name: Starting Project
    init: composer create-project laravel/laravel:^8.0 laravel &&
      mkdir -p laravel/packages/skijasi/posty-theme &&
      mv {,.}* laravel/packages/skijasi/posty-theme 2>/dev/null; true &&
      cd laravel/packages/skijasi &&
      git clone --branch 2.x --single-branch https://github.com/nadzorservera-indonesia/skijasi.git core &&
      git clone --branch 2.x --single-branch https://github.com/nadzorservera-indonesia/skijasi-post-module.git post-module &&
      git clone https://github.com/nadzorservera-indonesia/skijasi-content-module.git content-module &&
      cd ../../ &&
      cp packages/skijasi/posty-theme/.gitpod/AppServiceProvider.php app/Providers/AppServiceProvider.php &&
      cp packages/skijasi/posty-theme/.gitpod/app.php config/app.php &&
      cp packages/skijasi/posty-theme/.gitpod/composer.json composer.json &&
      cp .env.example .env &&
      composer update &&
      php artisan key:generate &&
      mysql -u root -e "create database laravel"
    command: php artisan skijasi:setup --force &&
      php artisan skijasi-post:setup &&
      php artisan skijasi-posty-theme:setup &&
      php artisan skijasi-content:setup &&
      cp packages/skijasi/posty-theme/.gitpod/webpack.mix.js webpack.mix.js &&
      sed -i 's/http:\/\/localhost//g' .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      sed -i 's/MIX_FRONTEND_URL=:8000/MIX_FRONTEND_URL=/g' .env &&
      sed -i "s|MIX_FRONTEND_URL=|MIX_FRONTEND_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|MIX_FRONTEND_URL=https://|MIX_FRONTEND_URL=https://8000-|g" .env &&
      sed -i 's/FILESYSTEM_DRIVER=local/FILESYSTEM_DRIVER=public/g' .env &&
      sed -i 's/MIX_DEFAULT_MENU=general/MIX_DEFAULT_MENU=general,post-module,content-module,posty-theme/g' .env &&
      sed -i 's/MIX_SKIJASI_MENU=${MIX_DEFAULT_MENU}/MIX_SKIJASI_MENU=${MIX_DEFAULT_MENU},post-module,content-module,posty-theme/g' .env &&
      echo -e "\nMIX_SKIJASI_PLUGINS=post-module,content-module,posty-theme" >> .env &&
      php artisan migrate &&
      php artisan db:seed --class="Database\Seeders\Skijasi\SkijasiSeeder" &&
      php artisan db:seed --class="Database\Seeders\Skijasi\Post\SkijasiPostModuleSeeder" &&
      php artisan db:seed --class="Database\Seeders\Skijasi\PostyTheme\SkijasiPostyThemeSeeder" &&
      php artisan db:seed --class="Database\Seeders\Skijasi\Content\SkijasiContentModuleSeeder" &&
      php artisan storage:link &&
      npm install &&
      php artisan skijasi:admin admin@admin.com --name=admin --username=admin --password=admin --confirm_password=admin --create && 
      npm run dev &&
      php artisan serve --host=0.0.0.0
ports:
  - port: 8000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer
    - PKief.material-icon-theme
